// Generated by delombok at Wed Aug 05 15:39:21 IST 2026
package com.velora.safety.controller;

import com.velora.safety.dto.IncidentRequest;
import com.velora.safety.dto.IncidentResponse;
import com.velora.safety.dto.SafeZoneResponse;
import com.velora.safety.entity.Incident;
import com.velora.safety.service.SafetyService;
import com.velora.safety.common.ApiResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import java.util.List;

@CrossOrigin(origins = "*", allowedHeaders = "*")
@RestController
@RequestMapping("/api/v1/safety")
@Tag(name = "Safety", description = "Incident reporting, safe zones, and proximity search")
public class SafetyController {
    private final SafetyService safetyService;

    private Long userId(String h) {
        if (h == null || h.isBlank()) return 1L;
        try {
            return Long.parseLong(h);
        } catch (NumberFormatException e) {
            return 1L;
        }
    }

    // ── SOS Endpoints ─────────────────────────────────────────────────────────
    @PostMapping("/sos")
    @Operation(summary = "Trigger emergency SOS alert")
    public ResponseEntity<ApiResponse<Object>> triggerSos(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader, @RequestBody(required = false) Object body) {
        Object response = safetyService.triggerSos(userId(userIdHeader), body);
        return ResponseEntity.ok(ApiResponse.success("SOS alert broadcasted successfully", response));
    }

    @PostMapping({"/sos/{alertId}/cancel", "/sos/{id}/cancel"})
    @Operation(summary = "Cancel emergency SOS alert with PIN verification")
    public ResponseEntity<ApiResponse<Object>> cancelSos(
            @PathVariable(value = "alertId", required = false) String alertIdStr,
            @PathVariable(value = "id", required = false) String idStr,
            @RequestBody(required = false) Object body) {
        String target = alertIdStr != null ? alertIdStr : idStr;
        Object response = safetyService.cancelSos(target, body);
        return ResponseEntity.ok(ApiResponse.success("SOS alert cancelled", response));
    }

    // ── Incidents ─────────────────────────────────────────────────────────────
    @PostMapping("/incidents")
    @Operation(summary = "Report a new incident")
    public ResponseEntity<ApiResponse<IncidentResponse>> reportIncident(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader, @Valid @RequestBody IncidentRequest request) {
        IncidentResponse response = safetyService.reportIncident(userId(userIdHeader), request);
        return ResponseEntity.ok(ApiResponse.success("Incident reported successfully", response));
    }

    @PostMapping(value = "/incidents/{id}/images", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @Operation(summary = "Upload images for an incident")
    public ResponseEntity<ApiResponse<List<String>>> uploadImages(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader, @PathVariable Long id, @RequestPart("files") List<MultipartFile> files) {
        List<String> urls = safetyService.uploadIncidentImages(id, userId(userIdHeader), files);
        return ResponseEntity.ok(ApiResponse.success("Images uploaded", urls));
    }

    @PutMapping("/incidents/{id}/status")
    @Operation(summary = "Update incident status (Police / Admin)")
    public ResponseEntity<ApiResponse<IncidentResponse>> updateIncidentStatus(
            @RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader,
            @PathVariable Long id,
            @RequestBody java.util.Map<String, String> body) {
        String statusStr = body.get("status");
        String notes = body.get("notes");
        Incident.IncidentStatus status = Incident.IncidentStatus.PENDING;
        if (statusStr != null) {
            try {
                status = Incident.IncidentStatus.valueOf(statusStr.toUpperCase());
            } catch (Exception e) {
                status = Incident.IncidentStatus.UNDER_REVIEW;
            }
        }
        IncidentResponse response = safetyService.updateIncidentStatus(id, status, userId(userIdHeader), notes);
        return ResponseEntity.ok(ApiResponse.success("Incident status updated successfully", response));
    }

    @GetMapping("/incidents/{id}")
    @Operation(summary = "Get incident by ID")
    public ResponseEntity<ApiResponse<IncidentResponse>> getIncident(@PathVariable Long id) {
        return ResponseEntity.ok(ApiResponse.success("Incident retrieved", safetyService.getIncident(id)));
    }

    @GetMapping("/incidents/my")
    @Operation(summary = "Get current user's incidents")
    public ResponseEntity<ApiResponse<Page<IncidentResponse>>> getMyIncidents(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader, @RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "10") int size) {
        Page<IncidentResponse> incidents = safetyService.getMyIncidents(userId(userIdHeader), PageRequest.of(page, size, Sort.by("createdAt").descending()));
        return ResponseEntity.ok(ApiResponse.success("Incidents retrieved", incidents));
    }

    @GetMapping("/incidents")
    @Operation(summary = "Get all incidents (police/admin)")
    public ResponseEntity<ApiResponse<Page<IncidentResponse>>> getAllIncidents(@RequestParam(required = false) Incident.IncidentStatus status, @RequestParam(required = false) Incident.IncidentType type, @RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "20") int size) {
        Page<IncidentResponse> incidents = safetyService.getAllIncidents(status, type, PageRequest.of(page, size, Sort.by("createdAt").descending()));
        return ResponseEntity.ok(ApiResponse.success("Incidents retrieved", incidents));
    }

    @DeleteMapping("/incidents/{id}")
    @Operation(summary = "Delete incident (reporter only)")
    public ResponseEntity<ApiResponse<Void>> deleteIncident(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader, @PathVariable Long id) {
        safetyService.deleteIncident(id, userId(userIdHeader));
        return ResponseEntity.ok(ApiResponse.success("Incident deleted", null));
    }

    // ── Geo-proximity ─────────────────────────────────────────────────────────
    @GetMapping("/incidents/nearby")
    @Operation(summary = "Get incidents near location")
    public ResponseEntity<ApiResponse<List<IncidentResponse>>> getNearbyIncidents(@RequestParam double lat, @RequestParam double lon, @RequestParam(defaultValue = "2000") double radius) {
        return ResponseEntity.ok(ApiResponse.success("Nearby incidents retrieved", safetyService.getNearbyIncidents(lat, lon, radius)));
    }

    // ── Safe Zones ────────────────────────────────────────────────────────────
    @GetMapping("/safe-zones")
    @Operation(summary = "Get all safe zones")
    public ResponseEntity<ApiResponse<Page<SafeZoneResponse>>> getAllSafeZones(@RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "20") int size) {
        return ResponseEntity.ok(ApiResponse.success("Safe zones retrieved", safetyService.getAllSafeZones(PageRequest.of(page, size))));
    }

    @PostMapping("/safe-zones")
    @Operation(summary = "Create safe zone")
    public ResponseEntity<ApiResponse<SafeZoneResponse>> createSafeZone(@RequestBody java.util.Map<String, Object> body) {
        return ResponseEntity.ok(ApiResponse.success("Safe zone created successfully", safetyService.createSafeZone(body)));
    }

    @GetMapping("/safe-zones/nearby")
    @Operation(summary = "Get safe zones near location")
    public ResponseEntity<ApiResponse<List<SafeZoneResponse>>> getNearbySafeZones(@RequestParam double lat, @RequestParam double lon, @RequestParam(defaultValue = "5000") double radius) {
        return ResponseEntity.ok(ApiResponse.success("Nearby safe zones retrieved", safetyService.getNearbySafeZones(lat, lon, radius)));
    }

    @GetMapping("/emergency-services/nearby")
    @Operation(summary = "Get nearby police stations and emergency hospitals")
    public ResponseEntity<ApiResponse<List<java.util.Map<String, Object>>>> getNearbyEmergencyServices(@RequestParam double lat, @RequestParam double lon, @RequestParam(defaultValue = "5000") double radius) {
        List<java.util.Map<String, Object>> services = List.of(
                java.util.Map.of("id", "ps_101", "name", "Central Police Station Hub", "type", "POLICE_STATION", "address", "Barakhamba Road, New Delhi", "latitude", lat + 0.005, "longitude", lon + 0.003, "contactNumber", "112", "distanceMeters", 450),
                java.util.Map.of("id", "hosp_202", "name", "AIIMS Emergency Trauma Care", "type", "HOSPITAL", "address", "Ansari Nagar, New Delhi", "latitude", lat - 0.008, "longitude", lon + 0.004, "contactNumber", "102", "distanceMeters", 1200)
        );
        return ResponseEntity.ok(ApiResponse.success("Nearby police and hospitals retrieved", services));
    }

    @GetMapping("/dashboard")
    @Operation(summary = "Get safety dashboard summary for location")
    public ResponseEntity<ApiResponse<java.util.Map<String, Object>>> getDashboard(
            @RequestParam(value = "lat", required = false, defaultValue = "13.0827") double lat,
            @RequestParam(value = "lng", required = false, defaultValue = "80.2707") double lng) {
        java.util.Map<String, Object> data = java.util.Map.of(
                "safetyScore", 85,
                "status", "SAFE",
                "activeAlerts", 0,
                "nearbyOfficers", 4,
                "safeZonesCount", 8,
                "latitude", lat,
                "longitude", lng
        );
        return ResponseEntity.ok(ApiResponse.success("Dashboard metrics retrieved", data));
    }

    @java.lang.SuppressWarnings("all")
    public SafetyController(final SafetyService safetyService) {
        this.safetyService = safetyService;
    }
}
